### PR TITLE
infra: Add AppImage build workflow

### PR DESCRIPTION
**Pull request by Samueru-sama**
This will produce an AppImage from the linux binaries, like I used to do [here](https://github.com/Samueru-sama/Ryujinx-AppImage). 

However I'm not sure how to include it in the release.yml 😅

Also this will only make an x86_64 AppImage.

### CODE REVIEW

**Comment by regginator** [comment]
Awesome! Yeah, I also think we could make the AppImage build process a standalone Bash script in `distribution/linux/` and use that in the release workflow, and for testing appimagetool locally.

build.yml is used for PR builds, we could probably include this directly in the release job for Linux x64 & arm64. I can into it today or tomorrow.

**Comment by Samueru-sama** [comment]
> Awesome! Yeah, I also think we could make the AppImage build process a standalone Bash script in `distribution/linux/` and use that in the release workflow, and for testing appimagetool locally.
> 
> build.yml is used for PR builds, we could probably include this directly in the release job for Linux x64 & arm64. I can look into it today or tomorrow.

I thought about making it an standalone script but I could not figure out how to integrate that with the existing releases, so I added it to the build.yml to use the already produced binaries as base for the appimage and turns even that doesn't work 😅

I'm not sure what to do from here.

**Comment by regginator** [comment]
Thanks so much for the help, merging this :smile:

Will also add this to the release workflow!

**Comment by Samueru-sama** [comment]
> Thanks so much for the help, merging this 😄
> 
> Will also add this to the release workflow!

Thank you but there a few details, one is this [mkdir](https://github.com/ryujinx-mirror/ryujinx/blob/mirror/master/distribution/linux/appimage/build-appimage.sh#L11) making an extra empty bin dir. 

The other is that the appimage and appimage.zsync have to be released separately and not as a compressed tar.gz file, the appimage is already compressed and both need to be able to be downloaded directly from the releases.

The .zsync file gets used for delta updates, that part of the script `"gh-releases-zsync|$GITHUB_REPOSITORY_OWNER|Ryujinx|latest|*.AppImage.zsync"` is info that gets embedded in the appimage and will tell AppImageUpdate to look for the latest  file that ends in `.AppImage.zsync` in this github repo (which github sets the `$GITHUB_REPOSITORY_OWNER` var for this already). 

This also means since there is an aarch64 appimage being made, the update info would need to change for something like this:

```
ARCH="$(uname -m)"
appimagetool --comp zstd --mksquashfs-opt -Xcompression-level --mksquashfs-opt 21 \
    -u "gh-releases-zsync|$GITHUB_REPOSITORY_OWNER|Ryujinx|latest|*-$ARCH.AppImage.zsync" \
    AppDir "$OUTDIR"/Ryujinx-"$ARCH".AppImage
```

That way appimageupdate doesn't get confused with the wrong .zsync file.

**Pull request merged**
