### PR TITLE
infra: don't repackage appimages and fix zsync files

### PR DESCRIPTION
**Pull request by Samueru-sama**
Now delta updates work: 

image

This is how the tool updates: 

image

EDIT: I also just included the version in the title of the AppImage as the [spec recommends](https://github.com/AppImage/AppImageSpec/blob/master/draft.md#type-2-image-format).

### CODE REVIEW

**Comment by regginator** [comment]
Thanks again, is it necessary we include the *.AppImage.zsync in builds? I feel that separating it would be both unnecessarily bloat the release artifcacts, and pretty annoying to actually update from a release. Also, putting the AppImage in an archive like this can preserve its executable permissions automatically.

**Comment by Samueru-sama** [comment]
> Thanks again, is it necessary we include the *.AppImage.zsync in builds? I feel that separating it would both unnecessarily bloat the release artifcacts, and be pretty annoying to actually update from a release. Also, putting the AppImage in an archive like this can preserve its executable permissions automatically.

https://docs.appimage.org/packaging-guide/distribution.html#do-not-put-appimages-into-other-archives

And the zsync has to be released as well. The other method is hosting it on a separate fixed url and modifying the script to point that url, which is what librewolf does.

Also how would it annoying to update from a release? this method prevents going back to the website to download the appimage manually (and also saves a bit of bandwidth since it doesn't download the entire appimage again).

**Comment by regginator** [comment]
> > Thanks again, is it necessary we include the *.AppImage.zsync in builds? I feel that separating it would both unnecessarily bloat the release artifcacts, and be pretty annoying to actually update from a release. Also, putting the AppImage in an archive like this can preserve its executable permissions automatically.
> 
> https://docs.appimage.org/packaging-guide/distribution.html#do-not-put-appimages-into-other-archives
> 
> And the zsync has to be released as well. The other method is hosting it on a separate fixed url and modifying the script to point that url, which is what librewolf does.
> 
> Also how would it annoying to update from a release? this method prevents going back to the website to download the appimage manually (and also saves a bit of bandwidth since it doesn't download the entire appimage again).

Ah.. I see lol, I was doing exactly what it said not to do 🤣

Will note hosting the zsync separately in the future, but since we're building AppImages for both x64 and arm64, I will also include zip_os_name in the AppImage file name.

**Comment by Samueru-sama** [comment]
> Will note hosting the zsync separately in the future, but since we're building AppImages for both x64 and arm64, I will also include zip_os_name in the AppImage file name.

The spec also says to not include linux in the title of the appimage 😅 but this isn't a big deal anyway, delta updates will still work.

**Comment by regginator** [comment]
That's fine, we can include just the arch nams

**Comment by regginator** [comment]
Does the file name need to be the exact same across releases?

**Comment by Samueru-sama** [comment]
> Does the file name need to be the exact same across releases?
>Looks like zsync handles this. 👍

The name of the AppImage? it can change, you can see it on my fork how the name looks now. 

image

What can't change is the last part of the name, that is `$ARCH.AppImage` that has to always have the same name for appimage update to find the right files. So you can include zip_os_name as long as it is before `$ARCH.AppImage`.

However iirc you cannot change the name of the AppImage or .zsync files after they are generated, whatever name they have it has to stay for this work. You can still rename the appimage on your PC after downloading it though, just that the name where it is hosted can't be changed after it is made.

**Comment by regginator** [comment]
This should be *fine*, but to keep with the naming scheme of the other binaries I'm using `${RUNNER_ARCH,,}` in the file name instead of `$ARCH`, which is meant explicitly for appimagetool..

image

**Comment by Samueru-sama** [comment]
> This should be _fine_, but to keep with the naming scheme of the other binaries I'm using `${RUNNER_ARCH,,}` in the file name instead of `$ARCH`, which is meant explicitly for appimagetool..

Yeah it is working: 

image

**Pull request merged**
